config/routes.rb
Rails.application.routes.draw do
  
  root 'main_page#home'

 
  get  '/work', to: 'main_page#work'
  get  '/services', to: 'main_page#services'
  get  '/blog', to: 'main_page#blog'
  get  '/contact', to: 'main_page#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
  def home
  end

  def work
  end

  def services
  end

  def blog
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Boomer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main_page/blog.html.erb
<h1>MainPage#blog</h1>
<p>Find me in app/views/main_page/blog.html.erb</p>

app/views/main_page/contact.html.erb
<h1>MainPage#contact</h1>
<p>Find me in app/views/main_page/contact.html.erb</p>

app/views/main_page/home.html.erb
<header >
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 <nav id="main-nav">
 <div class="container" id="menuc">
  <a href="#demo" class="menul" data-toggle="collapse">&#9776;</a>
  <div id="demo" class="collapse">

    <div class="navbar-text pull-right" style="align-items: left">
    	  <li class="columns" ><%= link_to "WORK",  work_path  %></li>
          <li class="columns"><%= link_to "SERVICE",  services_path  %></li>
          <li class="columns"><%= link_to "BLOG",  blog_path  %></li>
          <li class="columns"><%= link_to "CONTACT",  contact_path  %> </li>
	</div>
  </div>
</div>
  <div class="navbar-text pull-right" id="menu" style="align-items: left">
		  <%= link_to "WORK",  work_path  %>
		  <%= link_to "SERVICE",  services_path  %>
		  <%= link_to "BLOG",  blog_path  %>
		  <%= link_to "CONTACT",  contact_path  %> 

	</div>
</nav>

</header>
<body>
<div class="index">
	<div class="services">
		<div class="row">
			 <a class="row1"><div class="col-md-3"><img src="<%= asset_path 'shopping-cart.png' %>"> <br>eCommerce</div></a>
			  <a href=""><div class="col-md-3"><img src="<%= asset_path 'smartphone-call.png' %>"><br>Mobile Aplications</li></div></a>
			  <a href=""><div class="col-md-3"><img src="<%= asset_path 'work-tool.png' %>"><br>DevOps</div></a>
			   <a href=""><div class="col-md-3"><img src="<%= asset_path 'download.png' %>"><br>Software Development</div></a>
		</div>
	</div>
</div>
<div class="expanded">
	<div class="extext">
		<p>
			Boomer Digital provides an engaged, collaborative process while working with innovative open-source technologies. People are important to us, and we take the time to understand you and your business needs. We're here to help you design and execute clear, coherent IT and software strategies with ease.
		</p>
		<p>High Tech. High Touch.
	        Boomer.Digital</p>
 	</div>
</div>

<div class="columna" id="colm-1">
	<img src="<%= asset_path 'anun1.png' %>" alt="Avatar" class="image" style="width:100%">
	<span class="middle">
        <h4>Chipotle</h4>
        <a href="https://boomerdigital.net/portfolio/chipotle.html">
            View Details
        </a>
    </span>
</div>
<div class="columna">
	<img src="<%= asset_path 'anun2.png' %>" alt="Avatar" class="image">
	<span class="middle">
        <h4>Aloha</h4>
        <a href="https://boomerdigital.net/portfolio/chipotle.html">
            View Details
        </a>
    </span>
</div>
	<div class="columna">
	  	<img src="<%= asset_path 'anun3.png' %>" alt="Avatar" class="image">
	  	<span class="middle">
        <h4>Gather & Gown</h4>
        <a href="https://boomerdigital.net/portfolio/chipotle.html">
            View Details
        </a>
    </span>
</div>

<div id="clients" >
	<div class="col-xs-2">
		<a href="https://www.blueapron.com/" target="_blank">  
         	<img src="<%= asset_path 'apron.png' %>" class="Portf" id="imgap">
        </a>
	</div>
	<div class="col-xs-2">
		<a href="https://teeshirtpalace.com/" target="_blank"> 
			<img src="<%= asset_path 'teeshirt1.png' %>" class="Portf" id="imgpf">
		</a>
	</div>
	<div class="col-xs-2">
		<a href="https://www.mackweldon.com/" target="_blank">
			<img src="<%= asset_path 'mackW.png' %>" class="Portf">
		 </a>
	</div>
	<div class="col-xs-2">
		<a href="https://www.rockinstickers.com/" target="_blank"> 
			<img src="<%= asset_path 'rock.png' %>" class="Portf">
		</a>
	</div>
	<div class="col-xs-2">
		<a href="https://www.sherry-lehmann.com/" target="_blank"> 
			<img src="<%= asset_path 'sherry1.png' %>" class="Portf">
		</a>
	</div>
	<div class="col-xs-2">
		<a href="https://www.nourishsnacks.com/" target="_blank">
			<img src="<%= asset_path 'nourish1.png' %>" class="Portf">
		</a>
	</div>

	<h5>Want to see more? <a href="/portfolio.html" target="_blank" class="button radius">Visit Our Portfolio</a></h5>
</div>
<div class="row" style="background-color: white; padding-left: 2%;">
	<div class="col-xs-5">
	 	<img src="<%= asset_path 'docker.jpg' %>" alt="">
	</div>
	<div class="col-xs-5">
		<img src="<%= asset_path 'puppetlabs.png' %>" alt="" id="puppet-logo">		
	</div>
</div>
<div id="info">
	<h3 class="header-text">Connect with us</h3>
	<h6>Let us help you build amazing experiences</h6>
	<div class="row" style=" background-color: #f0f0f0;">
		<div class="col-md-6">
			<li class="columns large-5 small-12">
		        <i class="fi-mail"></i>
		        <span class="info">
		          hello@boomerdigital.net
		        </span>
      		</li>
		</div>
		<div class="col-md-6">
			<li class="columns large-5 small-12">
		        <i class="fi-telephone"></i>
		        <span class="info">
		          646-343-9058
		        </span>
      		</li>
		</div>
	</div>
</div>
</body>

app/views/main_page/services.html.erb
<h1>MainPage#services</h1>
<p>Find me in app/views/main_page/services.html.erb</p>

app/views/main_page/work.html.erb
<h1>MainPage#work</h1>
<p>Find me in app/views/main_page/work.html.erb</p>